import net.agkn.hll.HLL;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	public static void main(String[] args) {
		HLL h = new HLL(4, 8);
		h.addRaw(22);
		System.out.println(h.cardinality());
	}

}
